# Generated by Django 5.2.8 on 2025-11-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LAN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('subnet_vpn', models.CharField(max_length=25)),
                ('subnet_lan', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=1)),
                ('needs_deleted', models.BooleanField(default=True)),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='core.lan')),
            ],
        ),
        migrations.CreateModel(
            name='VPNCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True)),
                ('cert', models.TextField()),
                ('key', models.TextField()),
                ('key_pass', models.CharField(max_length=256)),
                ('pfs_cert_refid', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField()),
                ('need_renew', models.BooleanField(default=False)),
                ('renewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.lan')),
            ],
        ),
    ]
