# Generated by Django 5.2.8 on 2025-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpncert',
            old_name='key',
            new_name='_key',
        ),
        migrations.RenameField(
            model_name='vpncert',
            old_name='key_pass',
            new_name='_key_pass',
        ),
        migrations.RemoveField(
            model_name='code',
            name='id',
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lan',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='vpncert',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vpncert',
            constraint=models.UniqueConstraint(fields=('username', 'lan'), name='unique_user_per_lan'),
        ),
    ]
