# Generated by Django 5.2.8 on 2025-11-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_key_vpncert__key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpncert',
            name='_key_pass',
        ),
    ]
