# Generated by Django 5.2.8 on 2025-11-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_vpncert__key_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNClientConfig',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('certref', models.CharField(max_length=25)),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.lan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'lan'), name='Unique_config_user_per_lan')],
            },
        ),
    ]
