# Generated by Django 5.2.8 on 2025-11-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vpnclientconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclientconfig',
            name='conf_id',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vpnclientconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
