# Generated by Django 5.2.8 on 2025-11-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vpnclientconfig_conf_id_alter_vpnclientconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='caref',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
