# Generated by Django 5.2.8 on 2025-11-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_code_caref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpncert',
            name='_key',
        ),
    ]
